# Generated by Django 4.0.4 on 2022-05-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignupTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=20)),
                ('Password', models.CharField(max_length=70)),
                ('CnfPassword', models.CharField(max_length=70)),
            ],
        ),
    ]
